// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extractEventData
std::vector<NumericMatrix> extractEventData(NumericMatrix stats, NumericVector outcome, IntegerVector event_cluster, CharacterVector names);
RcppExport SEXP _dream_extractEventData(SEXP statsSEXP, SEXP outcomeSEXP, SEXP event_clusterSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event_cluster(event_clusterSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(extractEventData(stats, outcome, event_cluster, names));
    return rcpp_result_gen;
END_RCPP
}
// checkVarianceData
NumericVector checkVarianceData(List event_stats, int K);
RcppExport SEXP _dream_checkVarianceData(SEXP event_statsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(checkVarianceData(event_stats, K));
    return rcpp_result_gen;
END_RCPP
}
// remloglike
double remloglike(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remloglike(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remloglike(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}
// remloglikeOPTIM
double remloglikeOPTIM(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remloglikeOPTIM(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remloglikeOPTIM(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}
// remGradient
NumericVector remGradient(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remGradient(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remGradient(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}
// remHessian
NumericMatrix remHessian(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remHessian(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remHessian(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dream_extractEventData", (DL_FUNC) &_dream_extractEventData, 4},
    {"_dream_checkVarianceData", (DL_FUNC) &_dream_checkVarianceData, 2},
    {"_dream_remloglike", (DL_FUNC) &_dream_remloglike, 2},
    {"_dream_remloglikeOPTIM", (DL_FUNC) &_dream_remloglikeOPTIM, 2},
    {"_dream_remGradient", (DL_FUNC) &_dream_remGradient, 2},
    {"_dream_remHessian", (DL_FUNC) &_dream_remHessian, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_dream(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
