# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extractEventData <- function(stats, outcome, event_cluster, names) {
    .Call(`_dream_extractEventData`, stats, outcome, event_cluster, names)
}

checkVarianceData <- function(event_stats, K) {
    .Call(`_dream_checkVarianceData`, event_stats, K)
}

remloglike <- function(beta, event_stats) {
    .Call(`_dream_remloglike`, beta, event_stats)
}

remloglikeOPTIM <- function(beta, event_stats) {
    .Call(`_dream_remloglikeOPTIM`, beta, event_stats)
}

remGradient <- function(beta, event_stats) {
    .Call(`_dream_remGradient`, beta, event_stats)
}

remHessian <- function(beta, event_stats) {
    .Call(`_dream_remHessian`, beta, event_stats)
}

